name: .NET Build

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Dotnet Build
      run: dotnet build -c Release ILovePDF\ILovePDF.sln
